#!/bin/bash

jupyter serverextension enable --py nbserverproxy --sys-prefix

cd purly/js
npm install -g lerna
PUBLIC_URL="${JUPYTERHUB_OAUTH_CALLBACK_URL::-15}"
lerna bootstrap
lerna run build

cd ../py
pip install --upgrade pip
pip install .
